export default {
  products: [
    {
      _id: "1",
      name: "On the Essence of Chassidus",
      category: "Chassidus",
      image: "/images/chas1.jpg",
      price: 4,
      publisher: "Kehot",
      condition: "new",
      countInStock: 0,
    },
    {
      _id: "2",
      name: "On the Essence of Chassidus",
      category: "Chassidus",
      image: "/images/chas1.jpg",
      price: 4,
      publisher: "Kehot",
      condition: "new",

      countInStock: 8,
    },
    {
      _id: "3",
      name: "My Rebbe (Hebrew)",
      category: "Chassidic Thought",
      image: "/images/Rebbe1.jpg",
      price: 3,
      publisher: "Magid",
      condition: "new",

      countInStock: 6,
    },
    {
      _id: "4",
      name: "My Rebbe (Hebrew)",
      category: "Chassidic Thought",
      image: "/images/Rebbe1.jpg",
      price: 4,
      publisher: "Magid",
      condition: "new",
      countInStock: 5,
    },
    {
      _id: "5",
      name: "My Rebbe (Hebrew)",
      category: "Chassidic Thought",
      image: "/images/Rebbe1.jpg",
      price: 9,
      publisher: "Magid",
      condition: "new",
      countInStock: 2,
    },
  ],
};
